djnobangers/urls.py
from django.contrib import admin
from django.urls import include, path
from youtubeplayer import views as youtubeplayer_views

urlpatterns = [
    path('', youtubeplayer_views.index, name='index'),
    path('playlist/', include('playlist.urls')),
    path('youtubeplayer/', include('youtubeplayer.urls')),
    path('admin/', admin.site.urls),
]

playlist/urls.py
from django.urls import path

from . import views

app_name = 'playlist'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

youtubeplayer/urls.py
from django.urls import path

from . import views

app_name = 'youtubeplayer'
urlpatterns = [
    path('new', views.new_list, name='new_list'),
    path('<int:list_id>/', views.view_list, name='view_list'),
    path('<int:list_id>/add_url', views.add_url, name='add_url'),
]

playlist/models.py
from django.db import models

# Create your models here.

youtubeplayer/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class YTVideo(models.Model):
    def __str__(self):
        return self.title

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    title = models.CharField(max_length=200)
    url = models.CharField(max_length=200)
    next_url = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)

class List(models.Model):
    pass

class Item(models.Model):
    url = models.TextField(default='')
    title = models.TextField(default='')
    media = models.TextField(default='')
    list = models.ForeignKey(List, on_delete=models.CASCADE, default=None)

youtubeplayer/forms.py
from django import forms
from .models import YTVideo

class YTVideoForm(forms.ModelForm):
    class Meta:
        model = YTVideo
        fields = ('title', 'url')

    def clean(self):
        # do form checking here
        super().clean()

playlist/views.py
from django.shortcuts import render
from django.utils.safestring import mark_safe
import json

# Create your views here.
def index(request):
    return render(request, 'playlist/index.html', {})

def room(request, room_name):
    return render(request, 'playlist/room.html', {
        'room_name_json':mark_safe(json.dumps(room_name))
    })

youtubeplayer/views.py
from django.shortcuts import redirect, render
from .forms import YTVideoForm
from .models import YTVideo
from .models import Item, List
from django.http import HttpResponse
from .utils import parse_youtube_url
from youtubeplayer.youtube import YouTubeClient

def index(request):
    items = Item.objects.all()
    return render(request, 'youtubeplayer/index.html')

def new_list(request):
    list_ = List.objects.create()
    url = parse_youtube_url(request.POST['item_url'])
    title = YouTubeClient.get_youtube_title(url)
    Item.objects.create(url=url, title=title, media='youtube', list=list_)
    return redirect(f'/youtubeplayer/{list_.id}/')

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    return render(request, 'youtubeplayer/list.html', {'list': list_, 'list_id': list_id})

def add_url(request, list_id):
    list_ = List.objects.get(id=list_id)
    Item.objects.create(url=parse_youtube_url(request.POST['item_url']), title='', media='', list=list_)
    return redirect(f'/youtubeplayer/{list_.id}/')
    

playlist/templates/playlist/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Chat Room</title>
    </head>
    <body>
        What chat room would you like to enter?<br/>
        <input id="room-name-input" type="text" size="100"/><br/>
        <input id="room-name-submit" type="button" value="Enter"/>

        <script>
            document.querySelector('#room-name-input').focus();
            document.querySelector('#room-name-input').onkeyup = function(e) {
                if (e.keyCode === 13) {     // enter, return
                    document.querySelector('#room-name-submit').click();
                }
            };

            document.querySelector('#room-name-submit').onclick = function(e) {
                var roomName = document.querySelector('#room-name-input').value;
                window.location.pathname = '/playlist/' + roomName + '/';
            };
        </script>
    </body>
</html>

playlist/templates/playlist/room.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Chat Room</title>
    </head>
    <body>
        <textarea id="chat-log" cols="100" rows="2-"?></textarea>
        <input id="chat-message-input" type="text" size="100"/><br/>
        <input id="chat-message-submit" type="button" value="Send"/>
    </body>
    <script>
        var roomName = {{ room_name_json }};

        var chatSocket = new WebSocket(
            'ws://' + window.location.host + '/ws/playlist/' + roomName + '/');

        chatSocket.onmessage = function(e) {
            var data = JSON.parse(e.data);
            var message = data['message'];
            document.querySelector('#chat-log').value += (message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {     // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            var messageInputDom = document.querySelector('#chat-message-input');
            var message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));

            messageInputDom.value = '';
        };
    </script>
</html>

youtubeplayer/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DJ NoBangers</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">
    {% block css %}{% endblock %}
  </head>
 
  <body>
    {% block content %}{% endblock %}
  </body>

  {% block script %}{% endblock %}
</html>

youtubeplayer/templates/youtubeplayer/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2 jumbotron">
            <div class="text-center">
                <h1>Start a new playlist</h1>
                <form method="POST" action="/youtubeplayer/new">
                    <input name="item_url" id="id_new_item"
                    class="form-control input-lg"
                    placeholder="Enter a youtube link"/>
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

youtubeplayer/templates/youtubeplayer/list.html
{% extends 'base.html' %}

{% block css %}<link href="/static/list.css" rel="stylesheet">{% endblock %}

{% block content %}
  <div class="container">
    <br>
    <div class="row">
      <div class="embed-responsive embed-responsive-16by9 col-xs-12 text-center">
        <div id="player"></div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-8 offset-md-2 jumbotron">
        <div class="text-center">
          <h1>Your Playlist</h1>
          <input name="item_url" id="id_new_item" 
          class="form-control input-lg"
          placeholder="Enter a youtube link"/><br/>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <table id="id_list_table" class="table table-dark"/>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
    var player;
    var listID = {{ list_id }};
    var playlist = [];
    var table = document.querySelector('#id_list_table');
    var current_index = 0;

    // generate playlist in JS and HTML
    {% for item in list.item_set.all %}
      addSong('{{ item.url }}', '{{ item.title }}', '{{ item.media }}');
    {% endfor %}

    function addSong(url, title, media) {
      playlist.push({
        'url': url, 
        'title': title,
        'media': media,
      });
      var row = table.insertRow(-1);
      row.insertCell(0).innerHTML = table.rows.length + ": " + title;
      row.onclick = function() {
        current_index = row.rowIndex;
        player.loadVideoById(url);
        for (i = 0; i < table.rows.length; i++) {
          table.rows[i].style.backgroundColor = '#212529';
        }
        row.style.backgroundColor = '#6B7885';
      };
    }

    var playlistSocket = new WebSocket(
        'ws://' + window.location.host + '/ws/playlist/' + listID + '/');

    playlistSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        var title = data['title'];
        var media = data['media'];
        addSong(message, title, media);
    };

    playlistSocket.onclose = function(e) {
        console.error('Playlist socket closed unexpectedly');
    };

    document.querySelector('#id_new_item').onkeyup = function(e) {
        if (e.keyCode === 13) {     // enter, return
          var messageInputDom = document.querySelector('#id_new_item');
          var message = messageInputDom.value;
            
          var url = ytVidId(message);
          if (url) {
            playlistSocket.send(JSON.stringify({
                'message': url
            }));
          }

          messageInputDom.value = '';
        }
    };

    // 2. This code loads the IFrame Player API code asynchronously.
    var tag = document.createElement('script');

    tag.src = "https://www.youtube.com/iframe_api";
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    // 3. This function creates an <iframe> (and YouTube player)
    //    after the API code downloads.
    function onYouTubeIframeAPIReady() {
      player = new YT.Player('player', {
        height: '390',
        width: '640',
        videoId: '{{ list.item_set.first.url }}',
        events: {
          'onReady': onPlayerReady,
          'onStateChange': onPlayerStateChange
        }
      });
    }

    // 4. The API will call this function when the video player is ready
    function onPlayerReady(event) {
      event.target.playVideo();
      table.rows[0].style.backgroundColor = '#6B7885';
    }

    // 5. The API calls this function when the player's state changes.
    //    The function indicates that when playing a video (state=1),
    //    the player should play for six seconds and then stop.
    var done = false;
    function onPlayerStateChange(event) {
      if (event.data == YT.PlayerState.PLAYING && !done) {
        done = true;
      }
      if (event.data == YT.PlayerState.ENDED && done) {
        table.rows[current_index].style.backgroundColor = '#212529';
        current_index += 1;
        if (current_index < playlist.length) {
          player.loadVideoById(playlist[current_index]['url']);
          table.rows[current_index].style.backgroundColor = '#6B7885';
        }
      }
    }
    function stopVideo() {
      player.stopVideo();
    }

    // https://stackoverflow.com/a/10315969/624466
    function ytVidId(url) {
      var p = /^(?:https?:\/\/)?(?:www\.)?(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|watch\?.+&v=))((\w|-){11})(?:\S+)?$/;
      return (url.match(p)) ? RegExp.$1 : false;
    }

  </script>
{% endblock %}